// <auto-generated />
using System;
using InventoryReservation.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryReservation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260930170251_RichInventoryModel")]
    partial class RichInventoryModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")

            .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryReservation.Domain.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()

            .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()

            .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            UserName = "warehouse.demo"
                        });
                });

            modelBuilder.Entity("InventoryReservation.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()

            .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()

            .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Demo customer"
                        });
                });

            modelBuilder.Entity("InventoryReservation.Domain.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()

            .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SalesOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StockItemId");

                    b.ToTable("InventoryMovements");
                });

            modelBuilder.Entity("InventoryReservation.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()

            .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()

            .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()

            .HasMaxLength(256)

            .HasColumnType("character varying(256)");

                    b.Property<string>("Sku")
                        .IsRequired()

            .HasMaxLength(64)

            .HasColumnType("character varying(64)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "Demo",
                            IsActive = true,
                            Name = "Demo product",
                            Sku = "DEMO-001",
                            SupplierId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("InventoryReservation.Domain.SalesOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()

            .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()

            .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()

            .IsRequired()

            .HasColumnType("bytea");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("InventoryReservation.Domain.SalesOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()

            .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SalesOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("SalesOrderItems");
                });

            modelBuilder.Entity("InventoryReservation.Domain.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()

            .HasColumnType("uuid");

                    b.Property<int>("OnHandQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()

            .IsRequired()

            .HasColumnType("bytea");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ProductId", "WarehouseId")
                        .IsUnique();

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("InventoryReservation.Domain.StockReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()

            .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SalesOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalesOrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SalesOrderId");

                    b.HasIndex("StockItemId");

                    b.ToTable("StockReservations");
                });

            modelBuilder.Entity("InventoryReservation.Domain.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()

            .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()

            .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Demo supplier"
                        });
                });

            modelBuilder.Entity("InventoryReservation.Domain.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()

            .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()

            .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()

            .HasMaxLength(256)

            .HasColumnType("character varying(256)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "Demo street, 1",
                            Name = "Main warehouse",
                            Priority = 100
                        });
                });

            modelBuilder.Entity("InventoryReservation.Domain.InventoryMovement", b =>
                {
                    b.HasOne("InventoryReservation.Domain.StockItem", null)

            .WithMany("Movements")

            .HasForeignKey("StockItemId")

            .OnDelete(DeleteBehavior.Cascade)

            .IsRequired();
                });

            modelBuilder.Entity("InventoryReservation.Domain.SalesOrderItem", b =>
                {
                    b.HasOne("InventoryReservation.Domain.SalesOrder", null)

            .WithMany("Items")

            .HasForeignKey("SalesOrderId")

            .OnDelete(DeleteBehavior.Cascade)

            .IsRequired();
                });

            modelBuilder.Entity("InventoryReservation.Domain.StockItem", b =>
                {
                    b.HasOne("InventoryReservation.Domain.Product", "Product")

            .WithMany("StockItems")

            .HasForeignKey("ProductId")

            .OnDelete(DeleteBehavior.Cascade)

            .IsRequired();

                    b.HasOne("InventoryReservation.Domain.Warehouse", "Warehouse")

            .WithMany("StockItems")

            .HasForeignKey("WarehouseId")

            .OnDelete(DeleteBehavior.Cascade)

            .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("InventoryReservation.Domain.StockReservation", b =>
                {
                    b.HasOne("InventoryReservation.Domain.SalesOrder", null)

            .WithMany("Reservations")

            .HasForeignKey("SalesOrderId")

            .OnDelete(DeleteBehavior.Cascade)

            .IsRequired();

                    b.HasOne("InventoryReservation.Domain.StockItem", "StockItem")

            .WithMany()

            .HasForeignKey("StockItemId")

            .OnDelete(DeleteBehavior.Restrict)

            .IsRequired();

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("InventoryReservation.Domain.Product", b =>
                {
                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("InventoryReservation.Domain.SalesOrder", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("InventoryReservation.Domain.StockItem", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("InventoryReservation.Domain.Warehouse", b =>
                {
                    b.Navigation("StockItems");
                });
#pragma warning restore 612, 618
        }
    }
}

